import { type Config } from "tailwindcss";
import typography from "@tailwindcss/typography";

const colors = {
  current: "currentColor",
  transparent: "transparent",
  white: "#FFF",
  black: "#000",
  default: {
    text: "rgb(var(--color-default-text) / <alpha-value>)",
    bg: "rgb(var(--color-default-bg) / <alpha-value>)",
  },
  neutral: {
    1: "rgb(var(--color-grf-neutral-1) / <alpha-value>)",
    2: "rgb(var(--color-grf-neutral-2) / <alpha-value>)",
    3: "rgb(var(--color-grf-neutral-3) / <alpha-value>)",
    4: "rgb(var(--color-grf-neutral-4) / <alpha-value>)",
    5: "rgb(var(--color-grf-neutral-5) / <alpha-value>)",
    6: "rgb(var(--color-grf-neutral-6) / <alpha-value>)",
    7: "rgb(var(--color-grf-neutral-7) / <alpha-value>)",
    8: "rgb(var(--color-grf-neutral-8) / <alpha-value>)",
    9: "rgb(var(--color-grf-neutral-9) / <alpha-value>)",
    10: "rgb(var(--color-grf-neutral-10) / <alpha-value>)",
    11: "rgb(var(--color-grf-neutral-11) / <alpha-value>)",
    12: "rgb(var(--color-grf-neutral-12) / <alpha-value>)",
  },
  accent: {
    1: "rgb(var(--color-grf-accent-1) / <alpha-value>)",
    2: "rgb(var(--color-grf-accent-2) / <alpha-value>)",
    3: "rgb(var(--color-grf-accent-3) / <alpha-value>)",
    4: "rgb(var(--color-grf-accent-4) / <alpha-value>)",
    5: "rgb(var(--color-grf-accent-5) / <alpha-value>)",
    6: "rgb(var(--color-grf-accent-6) / <alpha-value>)",
    7: "rgb(var(--color-grf-accent-7) / <alpha-value>)",
    8: "rgb(var(--color-grf-accent-8) / <alpha-value>)",
    9: "rgb(var(--color-grf-accent-9) / <alpha-value>)",
    10: "rgb(var(--color-grf-accent-10) / <alpha-value>)",
    11: "rgb(var(--color-grf-accent-11) / <alpha-value>)",
    12: "rgb(var(--color-grf-accent-12) / <alpha-value>)",
  },
  success: {
    1: "rgb(var(--color-grf-success-1) / <alpha-value>)",
    2: "rgb(var(--color-grf-success-2) / <alpha-value>)",
    3: "rgb(var(--color-grf-success-3) / <alpha-value>)",
    4: "rgb(var(--color-grf-success-4) / <alpha-value>)",
    5: "rgb(var(--color-grf-success-5) / <alpha-value>)",
    6: "rgb(var(--color-grf-success-6) / <alpha-value>)",
    7: "rgb(var(--color-grf-success-7) / <alpha-value>)",
    8: "rgb(var(--color-grf-success-8) / <alpha-value>)",
    9: "rgb(var(--color-grf-success-9) / <alpha-value>)",
    10: "rgb(var(--color-grf-success-10) / <alpha-value>)",
    11: "rgb(var(--color-grf-success-11) / <alpha-value>)",
    12: "rgb(var(--color-grf-success-12) / <alpha-value>)",
  },
  warning: {
    1: "rgb(var(--color-grf-warning-1) / <alpha-value>)",
    2: "rgb(var(--color-grf-warning-2) / <alpha-value>)",
    3: "rgb(var(--color-grf-warning-3) / <alpha-value>)",
    4: "rgb(var(--color-grf-warning-4) / <alpha-value>)",
    5: "rgb(var(--color-grf-warning-5) / <alpha-value>)",
    6: "rgb(var(--color-grf-warning-6) / <alpha-value>)",
    7: "rgb(var(--color-grf-warning-7) / <alpha-value>)",
    8: "rgb(var(--color-grf-warning-8) / <alpha-value>)",
    9: "rgb(var(--color-grf-warning-9) / <alpha-value>)",
    10: "rgb(var(--color-grf-warning-10) / <alpha-value>)",
    11: "rgb(var(--color-grf-warning-11) / <alpha-value>)",
    12: "rgb(var(--color-grf-warning-12) / <alpha-value>)",
  },
  danger: {
    1: "rgb(var(--color-grf-danger-1) / <alpha-value>)",
    2: "rgb(var(--color-grf-danger-2) / <alpha-value>)",
    3: "rgb(var(--color-grf-danger-3) / <alpha-value>)",
    4: "rgb(var(--color-grf-danger-4) / <alpha-value>)",
    5: "rgb(var(--color-grf-danger-5) / <alpha-value>)",
    6: "rgb(var(--color-grf-danger-6) / <alpha-value>)",
    7: "rgb(var(--color-grf-danger-7) / <alpha-value>)",
    8: "rgb(var(--color-grf-danger-8) / <alpha-value>)",
    9: "rgb(var(--color-grf-danger-9) / <alpha-value>)",
    10: "rgb(var(--color-grf-danger-10) / <alpha-value>)",
    11: "rgb(var(--color-grf-danger-11) / <alpha-value>)",
    12: "rgb(var(--color-grf-danger-12) / <alpha-value>)",
  },
};

export default {
  content: ["./{routes,islands,app}/**/*.{ts,tsx}"],
  theme: {
    colors,
    extend: {
      borderColor: ({ theme }) => ({
        ...colors,
        DEFAULT: theme("colors.neutral.4", "currentColor"),
      }),
      ringColor: ({ theme }) => ({
        ...colors,
        DEFAULT: theme("colors.accent.6", "#3b82f6"),
      }),
    },
  },
  darkMode: ["selector", '[data-theme="dark"]'],
  plugins: [typography],
} satisfies Config;
